### ISSUE TITLE
contract.new不会要求输密码

### ISSUE THREAD

**Issue by qwang2505** [cryptape/ethereum-bootstrap#1]
环境：ubuntu 14.04.4，geth 1.4.0-unstable

按照bootstrap执行，在contract.new的时候不会要求输入密码，导致部署失败，错误信息是account is locked。

Workaround：

在contract.new前加上如下代码解锁账户：

personal.unlockAccount(web3.eth.accounts[0], "your account password");

**Comment by u2** [comment]
是的，使用前需要解锁Account。
