### ISSUE TITLE
执行到miner.start(1)后 没有出现Mined block

### ISSUE THREAD

**Issue by cm3235658** [cryptape/ethereum-bootstrap#13]
一直停在 checking DAG ，无法挖出区块 ，导致合约部署不上去~请问一下原因大概出现在哪里。
http://ethfans.org/jan/articles/51 这里面也有许多卡在miner.start(1)这一步~

**Comment by u2** [comment]
日志贴一下？要先checking dag 100%了，后面才会挖块

**Comment by hxzqlh** [comment]
开启挖矿后没反应，原因可能是私链的 genesis.json 配置无法生效，导致 geth 自动连到了公有链的配置，我的解决方法如下：
rm -rf ~/.ethash/
