### ISSUE TITLE
发送代币后

### ISSUE THREAD

**Issue by ucfyao** [cryptape/ethereum-bootstrap#15]
请问发送代币后，用哪个命令来检测成功。或者有直接监听的方式吗，谢谢

**Comment by u2** [comment]
只要查询交易状态就可以了，getTransaction，查看交易是否进block

**Comment by ucfyao** [comment]
正常发送eth我知道这个可用getTransaction查看状态。。比如发送了snt（一种基于eth发行的代币），接收者从哪个字段查看出收到了snt呢

**Comment by u2** [comment]
这种snt代币是一种Token合约，要根据交易的Receipt来判断，合约代码里一般会在交易成功时记录Log，只需要判断交易Receipt里是否有Log就可以了。

**Comment by ucfyao** [comment]
明白，也就是使用eth.getTransactionReceipt 查看logs 是null还是数组就可以识别了。非常感谢，我正在尝试解析topic
