### ISSUE TITLE
The method eth_compileSolidity does not exist/is not available at web3.js:3104:20

### ISSUE THREAD

**Issue by zjx** [cryptape/ethereum-bootstrap#18]

**Comment by zjx** [comment]
just found a way to work around the issue, refer the alternative 2 in the below article for details:

[https://ethereum.stackexchange.com/questions/15435/how-to-compile-solidity-contracts-with-geth-v1-6](https://ethereum.stackexchange.com/questions/15435/how-to-compile-solidity-contracts-with-geth-v1-6
)

**Comment by EighteenZi** [comment]
yes, 'web3.eth.compile.solidity' is no more supported. we have updated the bootstrap yet, and you can refer to the bootstrap now.
