### ISSUE TITLE
编译的时候提示找到选项

### ISSUE THREAD

**Issue by ghost** [cryptape/ethereum-bootstrap#23]
➜  contracts echo "var tokenCompiled=`solc --optimize --combined-json abi,bin,interface contracts/Token.sol`" > token.js
ERROR: Unknown option --optimize
➜  contracts echo "var tokenCompiled=`solc --optimise --combined-json abi,bin,interface contracts/Token.sol`" > token.js
ERROR: Unknown option --combined-json

**Comment by EighteenZi** [comment]
请确认一下solc是否安装正确。
按照下面方式重装试一下：
wget https://github.com/ethereum/solidity/releases/download/v0.4.19/solc-static-linux
chmod +x solc-static-linux
sudo mv solc-static-linux /usr/local/bin/solc

**Comment by ghost** [comment]
我的是Mac平台

**Comment by EighteenZi** [comment]
方法一：
brew update
brew upgrade
brew tap ethereum/ethereum
brew install solidity
brew linkapps solidity
来自： https://ethereum.stackexchange.com/questions/9513/how-do-i-install-solc-on-mac-osx-error-encountered-error-no-formulae-found-in

方法二：
参照：
http://solidity.readthedocs.io/en/develop/installing-solidity.html
