### ISSUE TITLE
编译的时候报错了

### ISSUE THREAD

**Issue by siophy** [cryptape/ethereum-bootstrap#3]
错误如下：
`
solc: exit status 1
Unknown exception during compilation.

```
at web3.js:3119:20
at web3.js:6023:15
at web3.js:4995:36
at <anonymous>:1:16
```

`
这也看不出来哪有问题，环境该装的都装了。

**Comment by u2** [comment]
solc 需要用c++ 版本的。
你用`solc --version`提示是什么？

**Comment by u2** [comment]
@siophy 可以关闭了么？
