### ISSUE TITLE
flag provided but not defined: -genesis  

### ISSUE THREAD

**Issue by ldh2068vip** [cryptape/ethereum-bootstrap#4]
show me  message 'flag provided but not defined: -genesis' while excute script ./bin/private_blockchain.sh , any guys help me ?THX

**Comment by ldh2068vip** [comment]
my geth version 1.4.10, flag genesis has been replaced init .

**Comment by ghost0913** [comment]
The latest versions of Geth (after 1.10.8-stable) do not support --rpc but fortunately, as you can see in the [Command-line Options](https://geth.ethereum.org/docs/interface/command-line-options), it has been replaced by the --http option.

With all rpc options replaced by their http equivalent:

--rpc => --http
--rpcapi => --http.api
--rpccorsdomain => --http.corsdomain
