### ISSUE TITLE
TypeError: 'getBalance' is not a function

### ISSUE THREAD

**Issue by ldh2068vip** [cryptape/ethereum-bootstrap#5]
while compile Token, aways tell me undefine, when I call getBalance, show me msg as below:

> var tokenSource = 'contract Token {     address issuer;     mapping (address => uint) balances;      event Issue(address account, uint amount);   }
> undefined
> var tokenCompiled = web3.eth.compile.solidity(tokenSource);
> undefined
> var contract = web3.eth.contract(tokenCompiled.Token.info.abiDefinition);
> undefined
> var initializer = {from: web3.eth.accounts[0], data: tokenCompiled.Token.code, gas: 300000};
> undefined
> var callback = function(e, contract){
> ...     if(!e) {
> ......       if(!contract.address) {
> .........         console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");
> .........       } else {
> .........         console.log("Contract mined!");
> .........         console.log(contract);
> .........       }
> ......     }
> ... };
> undefined
> var token = contract.new(initializer, callback);
> undefined
> token.getBalance(web3.eth.accounts[0])
> TypeError: 'getBalance' is not a function
>     at <anonymous>:1:1

**Comment by u2** [comment]
应该是没有解锁账号，你看下`token.address`，如果是`undefined`，应该是合约没有成功部署，部署合约前或者调用sendTransaction时都要先解锁下账号。

解锁账号：

```
> personal.unlockAccount(web3.eth.accounts[0])
Unlock account 0x3ae88fe370c39384fc16da2c9e768cf5d2495b48
Passphrase: 
true
```

另外，如果成功部署合约并成功打包到block中，会在日志里提示的，留意这两行

```
console.log("Contract mined!");
console.log(contract);
```

**Comment by u2** [comment]
@ldh2068vip 可以关闭了么？
