### ISSUE TITLE
--datadir data错误

### ISSUE THREAD

**Issue by xunfeng1980** [cryptape/ethereum-bootstrap#6]
lux@ubuntu:~/develop/ethereum-bootstrap-master$ ./bin/private_blockchain.sh
I0904 21:00:23.637664 ethdb/database.go:80] Allotted 128MB cache and 1024 file handles to data/chaindata
I0904 21:00:23.675093 ethdb/database.go:167] closed db:data/chaindata
I0904 21:00:23.675278 cmd/geth/main.go:329] instance: Geth/1.5.0-unstable/go1.6.2/linux
I0904 21:00:23.675315 ethdb/database.go:80] Allotted 128MB cache and 1024 file handles to data/chaindata
I0904 21:00:23.722509 eth/db_upgrade.go:346] upgrading db log bloom bins
I0904 21:00:23.759700 eth/db_upgrade.go:354] upgrade completed in 37.153451ms
I0904 21:00:23.761061 eth/backend.go:179] Protocol Versions: [63 62], Network Id: 31415926
I0904 21:00:23.771370 core/blockchain.go:204] Last header: #0 [19425866…] TD=131072
I0904 21:00:23.771566 core/blockchain.go:205] Last block: #0 [19425866…] TD=131072
I0904 21:00:23.771643 core/blockchain.go:206] Fast block: #0 [19425866…] TD=131072
I0904 21:00:23.778665 p2p/server.go:322] Starting Server
I0904 21:00:23.779812 p2p/server.go:576] Listening on [::]:30303
I0904 21:00:23.787421 core/blockchain.go:572] Chain manager stopped
I0904 21:00:23.787521 eth/handler.go:224] Stopping ethereum protocol handler...
I0904 21:00:23.787629 eth/handler.go:245] Ethereum protocol handler stopped
I0904 21:00:23.787769 core/tx_pool.go:163] Transaction pool stopped
I0904 21:00:23.787806 eth/backend.go:483] Automatic pregeneration of ethash DAG OFF (ethash dir: /home/lux/.ethash)

去掉--datadir data可以运行，链数据在~/.ethereum
lux@ubuntu:~/.ethereum$ ls
chaindata  data_bbb  geth.ipc  keystore  nodekey

**Comment by janx** [comment]
具体错误是什么？去掉`--datadir data`会使用默认的数据文件夹，有可能破坏正常钱包数据

**Comment by xunfeng1980** [comment]
I0904 21:07:22.027810 ethdb/database.go:167] closed db:data/chaindata
Fatal: Error starting protocol stack: listen unix data/geth.ipc: bind: no such file or directory
如果指定--datadir data的话，ipc文件没有被创建，刚刚抱歉，没有把错误粘贴上去。

**Comment by u2** [comment]
你试着修改下 `--datadir data`为绝对路径试下？

**Comment by xunfeng1980** [comment]
不知道为啥，用绝对路径在其他目录下都不行，在用户主目录下就可以。
失败：Fatal: Error starting protocol stack: listen unix /home/lux/develop/ethereum_bootstrap/data/geth.ipc: bind: no such file or directory

成功：I0905 20:35:22.793820 node/node.go:308] IPC endpoint opened: /home/lux/data/geth.ipc
I0905 20:35:22.794389 node/node.go:378] HTTP endpoint opened: http://localhost:8545

可能是因为我是直接软件源安装的geth，我编译一个试一下。谢谢大家！

**Comment by xunfeng1980** [comment]
# **问题已经找到，是我的问题，那个目录是一个符号链接，路径不对，谢谢大家**

**Comment by u2** [comment]
硬链是什么意思？

**Comment by xunfeng1980** [comment]
符号链接，所以一直路径不对
