### ISSUE TITLE
执行 web3.eth.getBalance(web3.eth.accounts[0]) 时报错？

### ISSUE THREAD

**Issue by wangfeiping** [cryptape/ethereum-bootstrap#7]
初学，照着文档部署操作，遇到报错，请问是什么问题？
`

> web3.eth.getBalance(web3.eth.accounts[0])
> invalid address
>     at web3.js:3887:15
>     at web3.js:4939:28
>     at web3.js:4938:12
>     at web3.js:4964:18
>     at web3.js:4989:23
>     at <anonymous>:1:1
> `

`

> miner.start(1)
> I0907 17:03:29.615659 eth/backend.go:454] Automatic pregeneration of ethash DAG ON (ethash dir: /root/.ethash)
> I0907 17:03:29.615778 eth/cpu_mining.go:35] Cannot start mining without etherbase address: etherbase address must be explicitly specified
> Cannot start mining without etherbase address: etherbase address must be explicitly specified
>     at web3.js:3119:20
>     at web3.js:6023:15
>     at web3.js:4995:36
>     at <anonymous>:1:1
> I0907 17:03:29.621127 eth/backend.go:461] checking DAG (ethash dir: /root/.ethash)
> `

**Comment by zhangsoledad** [comment]
你没有导入数据 或者是导入不成功 
把data目录清除，重试一下下面几个步骤
2. 导入测试账户私钥: `./bin/import_keys.sh`
3. 初始化blockchain: `./bin/private_blockchain_init.sh` 
输出的结果类似如下：  

``` shell
I0822 16:28:29.767646 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to data/chaindata I0822 16:28:29.773596 cmd/geth/main.go:299]
 successfully wrote genesis block and/or chain rule set: 19425866b7d3298a15ad79accf302ba9d21859174e7ae99ce552e05f13f0efa3 
```

4.启动私有链节点: `./bin/private_blockchain.sh`

**Comment by wangfeiping** [comment]
@zhangsoledad 哦，多谢多谢，照你说的试了几次就可以了。
