### ISSUE TITLE
新建一个ssh session, 切换到geth用户环境su - geth这句话是什么意思？

### ISSUE THREAD

**Issue by hzxscyq** [cryptape/ethereum-bootstrap#8]
问题1：新建一个ssh session, 切换到geth用户环境su - geth这句话是什么意思？
       我新开一个终端输入su - geth后报错，直接输入geth报错说Fatal: Error starting protocol stack:   listen    tcp :30303: bind: address already in use 

问题2：定义合约变量的时候var tokenSource=...返回的是undefined ，不知道有没有问题..

问题3：
编译合约代码的时候报错：
solc: exit status 1
ERROR: Unknown option --combined-json

```
at web3.js:3119:20
at web3.js:6023:15
at web3.js:4995:36
at <anonymous>:1:21
```

 不知道是不是编译器的问题？我单独下过solc，之后又下了cpp-ethereum，依然这样报错
谢谢

**Comment by u2** [comment]
你这是三个问题？请把你问题理通顺一点。

**Comment by hzxscyq** [comment]
已编辑原问题，谢谢

**Comment by u2** [comment]
1. man su
```
     su -l foo
            Simulate a login for user foo.
     su - foo
            Same as above.
```

2. 这个是javascript构赋值语句返回的结果undefined，没有问题
3. 你solc的版本是？
