### ISSUE TITLE
根据官方文档上的执行了geth 跑shell的时候报错啊  是执行不了geth 语句的意思

### ISSUE THREAD

**Issue by Vicky-w** [cryptape/ethereum-bootstrap#9]
`/go-ethereum/build/bin$ ./geth`   执行语句

官方文档下面也有private network的部署

你这里是写了shell脚本来简单操作

`I1012 15:00:02.055939 core/blockchain.go:975] imported 3 block(s) (0 queued 0 ignored) including 6 txs in 24.524855ms. #286965 [d30ab533 / 72e6be27]
I1012 15:00:05.591064 core/blockchain.go:975] imported 10 block(s) (0 queued 0 ignored) including 11 txs in 83.612587ms. #286975 [d475384f / a7c6c122]
I1012 15:00:07.109384 core/blockchain.go:975] imported 24 block(s) (0 queued 0 ignored) including 11 txs in 150.216637ms. #286999 [dbb52b87 / c3daa8e1]
I1012 15:00:09.178156 core/blockchain.go:975] imported 18 block(s) (0 queued 0 ignored) including 14 txs in 116.054661ms. #287017 [ce2274b2 / 5eb9fe43]
I1012 15:00:09.639333 core/blockchain.go:975] imported 41 block(s) (0 queued 0 ignored) including 20 txs in 285.514342ms. #287058 [d41b15eb / 0ee0cbd1]
I1012 15:00:09.824767 core/blockchain.go:975] imported 11 block(s) (0 queued 0 ignored) including 78 txs in 184.990816ms. #287069 [0c9d943f / 7e277550]
I1012 15:00:09.863798 core/blockchain.go:975] imported 4 block(s) (0 queued 0 ignored) including 6 txs in 38.701587ms. #287073 [8bbc20c2 / 33a04682]
I1012 15:00:10.312449 core/blockchain.go:975] imported 32 block(s) (0 queued 0 ignored) including 34 txs in 215.537185ms. #287105 [e1a06fbf / d961bc7c]
I1012 15:00:16.489958 core/blockchain.go:975] imported 433 block(s) (0 queued 0 ignored) including 939 txs in 3.467935625s. #287538 [c7be3ac7 / 3db82af3]
I1012 15:00:19.742567 core/blockchain.go:975] imported 575 block(s) (0 queued 0 ignored) including 630 txs in 3.245068438s. #288113 [1607f443 / 077ed302]
I1012 15:00:24.052639 core/blockchain.go:975] imported 560 block(s) (0 queued 0 ignored) including 469 txs in 3.254376982s. #288673 [b3338d7e / df8f76ab]
I1012 15:00:27.528088 core/blockchain.go:975] imported 556 block(s) (0 queued 0 ignored) including 537 txs in 3.465623679s. #289229 [b15053dc / 41c1fd77]
I1012 15:00:31.564592 core/blockchain.go:975] imported 625 block(s) (0 queued 0 ignored) including 517 txs in 4.02785118s. #289854 [8938469c / d15f8e75]
I1012 15:00:38.866256 core/blockchain.go:975] imported 769 block(s) (0 queued 0 ignored) including 1534 txs in 7.016311654s. #290623 [34a7a8fa / dc198611]
I1012 15:00:40.633076 core/blockchain.go:975] imported 298 block(s) (0 queued 0 ignored) including 256 txs in 1.761529942s. #290921 [bdd13838 / 69c22fc5]
I1012 15:00:47.222801 core/blockchain.go:975] imported 928 block(s) (0 queued 0 ignored) including 816 txs in 6.574631528s. #291849 [9571ee24 / 75957046]`
这里是执行geth的内容 会一直出新的内容停不下来   

然后新开了一个ssh跑你的内容   直接输入   `geth`  提示  `geth: command not found`

跑sh 提示内容如下：
`./bin/import_keys.sh
***** Using geth at: geth
***** Import all pre-funded private keys
***** Enter password for the new wallet: 
spawn  --datadir data account import ./private_keys/81063419f13cab5ac090cd8329d8fff9feead4a0.key
couldn't execute "": no such file or directory
    while executing
"spawn $geth --datadir data account import $key"
    (file "./private_keys/import.sh" line 7)
spawn  --datadir data account import ./private_keys/ca9f427df31a1f5862968fad1fe98c0a9ee068c4.key
couldn't execute "": no such file or directory
    while executing
"spawn $geth --datadir data account import $key"
    (file "./private_keys/import.sh" line 7)
spawn  --datadir data account import ./private_keys/3ae88fe370c39384fc16da2c9e768cf5d2495b48.key
couldn't execute "": no such file or directory
    while executing
"spawn $geth --datadir data account import $key"
    (file "./private_keys/import.sh" line 7)
spawn  --datadir data account import ./private_keys/bd2d69e3e68e1ab3944a865b3e566ca5c48740da.key
couldn't execute "": no such file or directory
    while executing
"spawn $geth --datadir data account import $key"
    (file "./private_keys/import.sh" line 7)
spawn  --datadir data account import ./private_keys/9da26fc2e1d6ad9fdd46138906b0104ae68a65d8.key
couldn't execute "": no such file or directory
    while executing
"spawn $geth --datadir data account import $key"
    (file "./private_keys/import.sh" line 7)
***** Done.`

在安装
`sudo npm install -g ethereumjs-testrpc`
`sudo npm install -g truffle`

也都会报错

`npm ERR! Or if that isn't available, you can get their info via:

> npm ERR!     npm owner ls scrypt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/ubuntu/npm-debug.log
> npm ERR! code 1
> 
> ^C
> ubuntu@us01:~$ npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls scrypt
> npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log
npm ERR! code 1`

我现在就是想试下私有部署  创建节点  对区块进行写入和读取的操作   区块的生成时间 和读取是不是一定要通过只能合约 共识进行操作

主要是后期要编写智能合约 做私有部署测试   做应用

**Comment by u2** [comment]
你geth和npm的安装都有问题
